### PR TITLE
Drop dependency on deprecated `gulp-util`

### LINKED ISSUE #53: Replace deprecated dependency gulp-util
[`gulp-util`](https://www.npmjs.com/package/gulp-util) has been deprecated recently. Continuing to use this dependency may prevent the use of your library with the latest release of Gulp 4 so **it is important to replace `gulp-util`**.

The [README.md](https://github.com/gulpjs/gulp-util) lists alternatives for all the components so a simple replacement should be enough.

Your package is popular but still relying on `gulp-util`, it would be good to publish a fixed version to npm as soon as possible.

See:
- https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
- https://github.com/gulpjs/gulp-util/issues/143

### PR DESCRIPTION
**Pull request by TheDancingCode**
Closes #53

### CODE REVIEW

**Review by demurgos — APPROVED** [review]
Looks good to me, thanks.

@MrBoolean 
Could we have this merged and published? Failing CI seems unrelated to this change, could you fix it?

**Comment by line0** [comment]
Nope, this is not yet good enough. gulp-run still depends on vinyl 0.4.6, which (from what i gathered) caused the whole ordeal first place. It's also possible that the vinyl test fails for that very reason. I haven't tried yet, but upgrading to vinyl 2.1 might fix the issue.

**Comment by m19c** [comment]
I agree with line0. I would suggest the following: we find out if `vinyl` is the problem - if so, we should try to update the dependency. If that does not solve the problem, we can consider making a new major release for gulp-run.

**Comment by FizzyGalacticus** [comment]
I just tried to look into this, and I found that the current master branch is failing tests as well.

image

**Comment by TheDancingCode** [comment]
The goal of this PR is not to fix issues you previously might have had with your plugin. It simply replaces a deprecated utility package by a functionally equivalent but smaller one. If the tests were failing before, they still will do so now, but the problem is unrelated to the PR or the changes it proposes.

I don't know the inner workings or the history of your package, so I'm not sure what the 'whole ordeal' is that you're referring to. So if this is 'not yet good enough', I'm afraid I can't help out any further. But once again, this PR is not trying to fix any and all problems you have with your plugin.

**Comment by FizzyGalacticus** [comment]
The "while ordeal" he's referring to is that the outdated `vinyl ` package is the cause of `gulp-util` breakage.

**Comment by FizzyGalacticus** [comment]
Here's a reference to why `gulp-util` is breaking packages in gulp v4: https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

**Comment by TheDancingCode** [comment]
Any progress on this?

**Comment by 2martens** [comment]
Is there any update over two years later?

**Pull request closed without merging**
